#!/usr/bin/env python

import json
import os
import subprocess
import sys

command = ['/usr/bin/env', 'mongo']

# If the second argument is an existing file, assume that this is the script
# to be executed. Otherwise, assume that it is the optional shebang argument.
if not os.path.exists(sys.argv[1]):
    command.extend(sys.argv.pop(1).split())

mongo_script_path = sys.argv[1]
mongo_script_args = sys.argv[2:]

variable_assignments = {'args': []}

for arg in mongo_script_args:
    try:
        variable_assignments['args'].append(json.loads(arg))
    except:
        if '=' in arg:
            key, value = arg.split('=', 1)

            try:
                value = json.loads(value)
            except:
                pass

            variable_assignments[key] = value
        else:
            variable_assignments['args'].append(arg)

if variable_assignments:
    command.extend(['--eval',
        'var ' + ','.join('{}={}'.format(key, json.dumps(value))
            for key, value in variable_assignments.items())])

command.append(mongo_script_path)

subprocess.call(command)
